SELECT * FROM TABLE1 --whenever i will give commit the output will be shown
--screen-2

BEGIN TRAN
--2
UPDATE TABLE2 SET T2_NAME='D' WHERE T2_ID=1
WAITFOR DELAY '00:00:05';

--4
UPDATE TABLE1 SET T1_NAME='B' WHERE T1_ID=1

COMMIT TRAN
SELECT T1_NAME FROM TABLE1 WHERE T1_ID=1
SELECT T2_NAME FROM TABLE2 WHERE T2_ID=1


--screen-2
--UPDATE LOCK EXAMPLE - SOLUTION
--NOTE  USE BOTH SCREEN AS A ADMIN USER
BEGIN TRAN
SELECT @@SPID AS SECONDTRANSACTIONID
EXEC SP_LOCK
--2
UPDATE TABLE2 SET T2_NAME='D' WHERE T2_ID=1
WAITFOR DELAY '00:00:05';

--4
UPDATE TABLE1 SET T1_NAME='B' WHERE T1_ID=1
COMMIT TRAN
SELECT T1_NAME FROM TABLE1 WHERE T1_ID=1
SELECT T2_NAME FROM TABLE2 WHERE T2_ID=1
