--FOR/AFTER TRIGGER FOR UPDATE
ALTER TRIGGER TRIGGER_DML_DEMO_UPDATE
ON CUST_DETAIL
FOR
UPDATE
AS
BEGIN 
DECLARE @CUST_ID INT, @CUST_NAME VARCHAR(10)
SELECT @CUST_ID= C_ID FROM INSERTED
IF (@CUST_ID IS NULL)
	PRINT ('CUSTOMER DATA NOT EXIST FOR THESE ID');
ELSE
BEGIN
	PRINT ('DATA UPDATED SUCCESSFULLY');
	INSERT INTO DML_LOGTABLE
	VALUES(@CUST_ID, 'UPDATE LOG ',GETDATE())
END
END

UPDATE CUST_DETAIL SET C_NAME='KS' WHERE C_ID=3
SELECT * FROM CUST_DETAIL
SELECT * FROM DML_LOGTABLE


-- FOR B2, B3 (AS I TALKED IN MORNING BY THIS WAY, CAN WE PERFORM?)
--STEP 1 CREATE TWO TABLES ONE MAIN AND ONE BACKUP AND INSERT DATA IN MAIN
CREATE TABLE MAIN_TABLE
(ID INT PRIMARY KEY, 
NAME VARCHAR(10))

INSERT INTO MAIN_TABLE
VALUES
(1,'HI'),
(2,'HELLO')

SELECT * FROM MAIN_TABLE
SELECT * FROM BACKUP_TABLE

CREATE TABLE BACKUP_TABLE
(ID INT PRIMARY KEY, 
NAME VARCHAR(10))

--STEP 2 CODE FOR TRIGGER 
ALTER TRIGGER T_DELETE
ON MAIN_TABLE
FOR DELETE 
AS
BEGIN 
DECLARE @M_ID INT,@M_NAME VARCHAR(10)
SELECT @M_ID=ID FROM INSERTED
INSERT INTO BACKUP_TABLE
VALUES
(@M_ID)
END

DELETE FROM MAIN_TABLE WHERE ID=1